NEW Add GitHub Action for publishing to NPM
silverstripe/webpack-config pull request #46
Opened 2020-05-24 23:16 UTC by Cheddam

This will trigger a publish of the module whenever we create a new release, saving time for the few developers with access to the `@silverstripe` NPM org. Requires a `YARN_TOKEN` secret to be added to the repository.

2020-05-25 00:11 UTC, Cheddam commented
This needs a little more thought - it relies on the `version` being set correctly in `package.json`, so still involves some double-handling. I'll look at adjusting it to either commit the new version back into `package.json` or to trigger the GitHub release based on the version being changed in `package.json`.

2020-07-23 02:58 UTC, emteknetnz requested changes
What will trigger a release? Anything being merged into master?

What happens if `version` is not updated? Will it overwrite the old version in npm?

2020-07-23 03:03 UTC, Cheddam commented
> What will trigger a release?

Creating a new Release in GitHub.

> What happens if `version` is not updated? Will it overwrite the old version in npm?

Excellent question - nope, it'll throw an error. I'll add docs on the release process to this PR.

2020-07-23 03:11 UTC, emteknetnz commented
You could probably do something to get the latest tag name from the release

e.g. `${{ github.event.release.tag_name }}`
https://github.community/t/how-to-get-just-the-tag-name/16241/19

and then use that to populate `yarn publish --new-version <version>`
https://classic.yarnpkg.com/en/docs/cli/publish/

2020-07-23 03:58 UTC, Cheddam commented
The trouble with that is keeping the `version` in `package.json` up to date, which would require committing this back after the publish is triggered. I'm not sure how important it is to keep it in an accurate state, but I'd rather continue keeping it updated for now.

The foremost issue this automation intends to resolve is enabling releases from contributing / core committers who don't have access to the NPM organisation. We can look into more advanced tooling like [semantic-release](https://semantic-release.gitbook.io/) to further automate this process later.

2020-07-23 04:05 UTC, emteknetnz requested changes
We should make some small changes to the readme

2020-07-23 04:05 UTC, emteknetnz commented on README.md
> +This package will be automatically published to NPM when the following steps are taken:
```suggestion
This package will be automatically published to NPM when the following steps are taken.  These steps MUST be done in this order:
```

2020-07-23 04:05 UTC, emteknetnz commented on README.md
> +1. The `version` key in `package.json` is updated on `master`
```suggestion
1. The `version` key in `package.json` is updated on `master`.  It's OK to edit this directly within github without a separate pull-request.
```

2022-11-29 03:21 UTC, GuySartorelli commented
We're doing away with the `master` branch to conform with the branching strategy we use on all our other repos - this PR will need to be updated to match, assuming we are still going ahead with this.

2023-10-08 22:47 UTC, GuySartorelli commented
Closing since we simply haven't done anything with this, and we haven't been updating this with any frequency anyway. If this becomes a problem for us in the future we'll look at doing something like this again.

2023-10-08 22:47 UTC, closed without merging